version: '3.8'

services:
  backend:
    build:
      context: ./src/main/java/AmbulanceBackend
    ports:
      - "8080:8080"
    container_name: ambulance-backend

  frontend:
    build:
      context: ./ambulance-frontend
    ports:
      - "3000:80"
    container_name: ambulance-frontend
    depends_on:
      - backend
